  
name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [12]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@master
      with:
        version: ${{ matrix.node_version }}
    - uses: chrislennon/action-aws-cli@v1.1
      # All commands after this point have access to the AWS CLI
    - run: aws ssm get-parameter --name userPoolId-$NODE_CONFIG_ENV | jq -r ".Parameter.Value"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # - name: yarn install
    #   run: yarn install
    # - name: yarn build
    #   run: yarn build
    # - name: deploy
    #   uses: jakejarvis/s3-sync-action@master
    #   with:
    #     args: --acl public-read --follow-symlinks --delete
    #   env:
    #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET}}
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: 'ap-southeast-2'   # optional: defaults to us-east-1
    #     SOURCE_DIR: 'dist'  
    #     DEST_DIR: 'subdirectory'
    # - name: invalidate cloudfront
    #   uses: awact/cloudfront-action@master
    #   env:
    #     SOURCE_DIR: './subdirectory'
    #     AWS_REGION: 'ap-southeast-2'
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
